/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118534-g6232f416b1-20250224"
#endif /* AVUTIL_FFVERSION_H */
